name: Enforce Branch Naming Convention

on:
  create:
    branches:
      - '**'

jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          if [[ ! "${GITHUB_REF#refs/heads/}" =~ ^(feature|bugfix|release)/[a-z0-9._-]+$ ]]; then
            echo "Branch name does not follow the naming convention: (feature|bugfix|release)/[a-z0-9._-]"
            exit 1
          fi
